// policy_exec_cpp.cpp
// Subscribe COMMANDS from ZRTDB.

#include "inc/CONTROLER.h" // merged per-APP header (generated by zrtdb_model)

#include <atomic>
#include <chrono>
#include <cstdint>
#include <iostream>
#include <string>
#include <thread>
#include <type_traits>

namespace zrtdb_demo {

class SnapshotReadScope final {
public:
    SnapshotReadScope() { SnapshotReadLock_(); }
    ~SnapshotReadScope() { SnapshotReadUnlock_(); }

    SnapshotReadScope(const SnapshotReadScope&) = delete;
    SnapshotReadScope& operator=(const SnapshotReadScope&) = delete;
};

static zrtdb_app_controler_ctx_t g_ctx;

static void db_init()
{
    if (zrtdb_app_controler_init(&g_ctx) < 0) {
        std::cerr << "ZRTDB init failed (CONTROLER)" << std::endl;
        std::abort();
    }
}

static void handle_command_row(int row, std::int64_t last_sig)
{
    const auto id = g_ctx.CONTROL_CONTROLPTR->ID_COMMANDS[row];
    const auto val = g_ctx.CONTROL_CONTROLPTR->VAL_COMMANDS[row];
    const auto sig = g_ctx.CONTROL_CONTROLPTR->SIG_COMMANDS[row];
    const auto status = g_ctx.CONTROL_CONTROLPTR->STATUS_COMMANDS[row];
    const char* info = g_ctx.CONTROL_CONTROLPTR->INFO_COMMANDS[row];

    std::cout
        << "consume: row=" << (row + 1)
        << " id=" << id
        << " val=" << val
        << " sig=" << sig
        << " status=" << status
        << " info=" << (info ? info : "")
        << "\n";

    if (last_sig >= 0 && static_cast<std::int64_t>(sig) > 0 && static_cast<std::int64_t>(sig) <= last_sig) {
        std::cerr << "WARN: non-increasing SIG observed (sig=" << sig << ", last_sig=" << last_sig
                  << "). Possible overwrite / missed updates.\n";
    }
}

} // namespace zrtdb_demo

int main()
{
    zrtdb_demo::db_init();

    using LvType = std::remove_reference_t<decltype(zrtdb_demo::g_ctx.CONTROL_CONTROL->LV_COMMANDS)>;

    LvType prev_lv = 0; // 1-based
    std::int64_t last_sig = -1;

    for (;;) {
        // Acquire-load LV.
        // NOTE: partitions are packed to match mmdb layout; avoid std::atomic_ref on packed fields.
        LvType lv_now = *reinterpret_cast<volatile LvType*>(&zrtdb_demo::g_ctx.CONTROL_CONTROL->LV_COMMANDS);
        std::atomic_thread_fence(std::memory_order_acquire);
        if (lv_now != prev_lv) {
            prev_lv = lv_now;
            int n = (int)lv_now;
            if (n > 0 && n <= ZRTDB_CONTROL_MX_COMMANDS) {
                const int row = n - 1;
                if (zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->STATUS_COMMANDS[row] != 2) {
                    zrtdb_demo::handle_command_row(row, last_sig);
                    last_sig = (std::int64_t)zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->SIG_COMMANDS[row];
                    zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->STATUS_COMMANDS[row] = 2;
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
