// policy_gen_cpp.cpp
// Publish COMMANDS into ZRTDB with RAII snapshot batch + release commit.

#include "inc/CONTROLER.h" // merged per-APP header (generated by zrtdb_model)

#include <atomic>
#include <chrono>
#include <cstring>
#include <ctime>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <type_traits>

using std::cout;
using std::endl;

namespace zrtdb_demo {

static std::string now_text_local()
{
    std::time_t t = std::time(nullptr);
    std::tm tm {};
    localtime_r(&t, &tm);

    std::ostringstream oss;
    oss << std::put_time(&tm, "%F %T");
    return oss.str();
}

// RAII wrapper: enter/leave a cooperative "write batch" for snapshot consistency.
class SnapshotBatch final {
public:
    SnapshotBatch() { SnapshotReadLock_(); }
    ~SnapshotBatch() { SnapshotReadUnlock_(); }

    SnapshotBatch(const SnapshotBatch&) = delete;
    SnapshotBatch& operator=(const SnapshotBatch&) = delete;
};

static zrtdb_app_controler_ctx_t g_ctx;

static void db_init()
{
    if (zrtdb_app_controler_init(&g_ctx) < 0) {
        std::cerr << "ZRTDB init failed (CONTROLER)" << std::endl;
        std::abort();
    }
}

static void write_info_text(int row, const std::string& text)
{
    // Fixed-size string: keep NUL termination.
    std::strncpy(g_ctx.CONTROL_CONTROLPTR->INFO_COMMANDS[row], text.c_str(), 120);
    g_ctx.CONTROL_CONTROLPTR->INFO_COMMANDS[row][119] = '\0';
}

} // namespace zrtdb_demo

int main()
{
    zrtdb_demo::db_init();

    const int mx = ZRTDB_CONTROL_MX_COMMANDS;
    int cmd_counter = 0;

    using LvType = std::remove_reference_t<decltype(zrtdb_demo::g_ctx.CONTROL_CONTROL->LV_COMMANDS)>;

    for (;;) {
        const int row = static_cast<int>(cmd_counter % mx); // 0-based
        ++cmd_counter;

        {
            zrtdb_demo::SnapshotBatch batch;

            zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->STATUS_COMMANDS[row] = 0;
            zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->VAL_COMMANDS[row] = 3.1415926535;
            zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->ID_COMMANDS[row] = 200;

            // Make SIG monotonic so readers can detect drops/gaps.
            zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->SIG_COMMANDS[row] =
                static_cast<decltype(zrtdb_demo::g_ctx.CONTROL_CONTROLPTR->SIG_COMMANDS[row])>(cmd_counter);

            zrtdb_demo::write_info_text(row, zrtdb_demo::now_text_local() + " 发出控制指令");

            // Publish LV with release semantics.
            // NOTE: partitions are packed to match mmdb layout; avoid std::atomic_ref on packed fields.
            std::atomic_thread_fence(std::memory_order_release);
            *reinterpret_cast<volatile LvType*>(&zrtdb_demo::g_ctx.CONTROL_CONTROL->LV_COMMANDS) =
                static_cast<LvType>(row + 1); // 1-based LV
        }

        std::cout << "publish: seq=" << cmd_counter << " lv=" << (row + 1) << "\n";

        if (cmd_counter == 6) {
            cout << "测试快照的写入 COMMANDS LV = " << zrtdb_demo::g_ctx.CONTROL_CONTROL->LV_COMMANDS << endl;
            char path[512];
            SaveSnapshot_(path, sizeof(path));
            std::cout << "snapshot=" << path << "\n";
        }

        std::this_thread::sleep_for(std::chrono::seconds(5));
    }
}
